#!/bin/sh

# Set these paths appropriately

BIN="/Users/minanarayanan/desktop/files/comp4970/research/authorid_pfp/src/pos_tagger/bin"
CMD="/Users/minanarayanan/desktop/files/comp4970/research/authorid_pfp/src/pos_tagger/cmd"
LIB="/Users/minanarayanan/desktop/files/comp4970/research/authorid_pfp/src/pos_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
