#!/bin/sh

# Set these paths appropriately

BIN="/Users/minanarayanan/desktop/files/comp4970/research/authorid_pfp/src/pos_tagger/bin"
CMD="/Users/minanarayanan/desktop/files/comp4970/research/authorid_pfp/src/pos_tagger/cmd"
LIB="/Users/minanarayanan/desktop/files/comp4970/research/authorid_pfp/src/pos_tagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
